insert into products (product_name, price, description) values ('Parsley Italian - Fresh', '8', 'Revision of Int Fix in R Metatarsotars Jt, Open Approach');
insert into products (product_name, price, description) values ('Island Oasis - Strawberry', '40', 'Drainage of L Foot Bursa/Lig with Drain Dev, Open Approach');
insert into products (product_name, price, description) values ('Table Cloth - 53x69 Colour', '110', 'Replace R Cephalic Vein w Synth Sub, Perc Endo');
insert into products (product_name, price, description) values ('Kellogs Cereal In A Cup', '57', 'Inspection of Lumbosacral Joint, Percutaneous Approach');
insert into products (product_name, price, description) values ('Munchies Honey Sweet Trail Mix', '523', 'Insert Infusion Dev in L Int Jugular Vein, Open');
insert into products (product_name, price, description) values ('French Pastries', '48536', 'Excision of Large Intestine, Via Opening');
insert into products (product_name, price, description) values ('Pasta - Orzo Dry', '50', 'Drainage of Left Lacrimal Gland, Perc Approach, Diagn');
insert into products (product_name, price, description) values ('Rosemary - Fresh', '645', 'Excision of Left Pulmonary Vein, Percutaneous Approach');
insert into products (product_name, price, description) values ('Pepper - Black Crushed', '1079', 'Detachment at Right Foot, Partial 3rd Ray, Open Approach');
insert into products (product_name, price, description) values ('Wine - Spumante Bambino White', '7', 'Excision of Abdominal Wall, Percutaneous Approach');
insert into products (product_name, price, description) values ('Chicken Breast Wing On', '30720', 'Compression of Neck using Pressure Dressing');
insert into products (product_name, price, description) values ('Artichoke - Bottom Canned', '8', 'Repair Left Knee Joint, Open Approach');
insert into products (product_name, price, description) values ('Sour Puss Raspberry', '42', 'Release Left Inner Ear, Open Approach');
insert into products (product_name, price, description) values ('Soup - Campbells Classic Chix', '563', 'Bypass R Int Iliac Art to B Femor A w Nonaut Sub, Open');
insert into products (product_name, price, description) values ('Syrup - Monin Amaretta', '646', 'Magnetic Resonance Imaging (MRI) of Neck using Oth Contrast');
insert into products (product_name, price, description) values ('Oil - Cooking Spray', '5408', 'Destruction of L Low Extrem Bursa/Lig, Perc Approach');
insert into products (product_name, price, description) values ('Sage Ground Wiberg', '5', 'Release Left Femoral Vein, Percutaneous Endoscopic Approach');
insert into products (product_name, price, description) values ('Cheese - Brie danish', '674', 'Fusion of Left Shoulder Joint with Autol Sub, Open Approach');
insert into products (product_name, price, description) values ('Bread - Raisin Walnut Pull', '8724', 'Fluoroscopy of Left Common Carotid Artery using Oth Contrast');
insert into products (product_name, price, description) values ('Soupcontfoam16oz 116con', '3016', 'Replace R Ext Iliac Vein w Autol Sub, Perc Endo');
insert into products (product_name, price, description) values ('Puree - Strawberry', '100', 'Division of Left Lacrimal Bone, Percutaneous Approach');
insert into products (product_name, price, description) values ('Transfer Sheets', '35', 'Drainage of Gastric Artery with Drain Dev, Open Approach');
insert into products (product_name, price, description) values ('Celery Root', '8', 'Destruction of Perineum Bursa/Lig, Perc Endo Approach');
insert into products (product_name, price, description) values ('Tarts Assorted', '3838', 'Revision of Autol Sub in R Metatarsotars Jt, Perc Approach');
insert into products (product_name, price, description) values ('Wine - Prosecco Valdobiaddene', '56139', 'Bypass L Axilla Art to R Up Arm Art w Autol Art, Open');
insert into products (product_name, price, description) values ('Shrimp - Baby Cold Water', '9333', 'Destruction of Left Shoulder Tendon, Perc Endo Approach');
insert into products (product_name, price, description) values ('Ice Cream - Vanilla', '4', 'Revision of Autol Sub in R Low Femur, Open Approach');
insert into products (product_name, price, description) values ('Onions - Green', '100', 'Drainage of L Shoulder Tendon with Drain Dev, Perc Approach');
insert into products (product_name, price, description) values ('Allspice - Jamaican', '92042', 'Transfer Left Wrist Bursa and Ligament, Open Approach');
insert into products (product_name, price, description) values ('Bread - Roll Italian', '31544', 'Insert Intralum Dev in Sup Vena Cava, Perc Endo');
insert into products (product_name, price, description) values ('Soup - Campbells Bean Medley', '1070', 'Drainage of Left Carpal Joint, Percutaneous Approach');
insert into products (product_name, price, description) values ('Corn - On The Cob', '178', 'Fluoroscopy of Left Toe(s)');
insert into products (product_name, price, description) values ('Squash - Pepper', '42906', 'Transfer Facial Nerve to Abducens Nerve, Open Approach');
insert into products (product_name, price, description) values ('Snapple Lemon Tea', '15', 'Bypass Jejunum to Jejunum with Synth Sub, Open Approach');
insert into products (product_name, price, description) values ('Chicken - Base', '6', 'Excision of Larynx, Endo');
insert into products (product_name, price, description) values ('Island Oasis - Strawberry', '4106', 'Bypass Bi Ureter to L Ureter with Synth Sub, Open Approach');
insert into products (product_name, price, description) values ('Bread - Roll Whole Wheat', '2', 'Drainage of Pituitary Gland, Perc Endo Approach, Diagn');
insert into products (product_name, price, description) values ('Glass Clear 8 Oz', '84305', 'Bypass Hepatic Vein to Low Vein w Autol Art, Perc Endo');
insert into products (product_name, price, description) values ('Wine - Jaboulet Cotes Du Rhone', '5454', 'Extirpation of Matter from L Pelvic Bone, Perc Endo Approach');
insert into products (product_name, price, description) values ('Asparagus - White Fresh', '79', 'Revision of Drain Dev in R Metatarsotars Jt, Perc Approach');
insert into products (product_name, price, description) values ('Steel Wool', '41', 'Removal of Infusion Device from L Tarsal Jt, Perc Approach');
insert into products (product_name, price, description) values ('Flour - Pastry', '4837', 'Replacement of Hepatic Artery with Nonaut Sub, Open Approach');
insert into products (product_name, price, description) values ('Food Colouring - Orange', '646', 'Repair Carina, Percutaneous Endoscopic Approach');
insert into products (product_name, price, description) values ('Shampoo - Tetleys', '8554', 'Extirpation of Matter from R Lacrimal Bone, Perc Approach');
insert into products (product_name, price, description) values ('Cardamon Seed / Pod', '700', 'Revision of Spacer in Lumbar Vertebral Joint, Perc Approach');
insert into products (product_name, price, description) values ('Salmon - Atlantic Fresh Whole', '1', 'Drainage of Nasal Septum with Drainage Device, Open Approach');
insert into products (product_name, price, description) values ('Salmon - Roasted Cooked', '6', 'Repair Right Trunk Bursa and Ligament, Percutaneous Approach');
insert into products (product_name, price, description) values ('Wine - Spumante Bambino White', '4', 'Reposition Rectum, Open Approach');
insert into products (product_name, price, description) values ('Chocolate Bar - Smarties', '6564', 'Destruction of L Post Tib Art, Perc Endo Approach');
insert into products (product_name, price, description) values ('Salmon - Tenderloin', '53', 'Destruction of Inferior Mesenteric Artery, Open Approach');
insert into products (product_name, price, description) values ('Cheese - Bocconcini', '54', 'Nonimag Nucl Med Prob of Up Extrem using Indium 111');
insert into products (product_name, price, description) values ('Soup - Campbells Bean Medley', '194', 'Drainage of Right Acetabulum, Perc Endo Approach, Diagn');
insert into products (product_name, price, description) values ('Soup - Chicken And Wild Rice', '7', 'Revision of Drain Dev in Pituitary Gland, Perc Endo Approach');
insert into products (product_name, price, description) values ('Pesto - Primerba Paste', '16730', 'Excision of Left Foot Bursa and Ligament, Perc Endo Approach');
insert into products (product_name, price, description) values ('Myers Planters Punch', '46822', 'Removal of Bone Stim from Facial Bone, Perc Endo Approach');
insert into products (product_name, price, description) values ('Cheese - Mascarpone', '17', 'Supplement Right Orbit with Autol Sub, Perc Endo Approach');
insert into products (product_name, price, description) values ('Southern Comfort', '2011', 'Excision of Pulmonary Valve, Perc Endo Approach, Diagn');
insert into products (product_name, price, description) values ('Wine - Redchard Merritt', '974', 'Destruction of Right Ankle Joint, Open Approach');
insert into products (product_name, price, description) values ('Pasta - Bauletti Chicken White', '16', 'Extirpation of Matter from Left Lower Femur, Perc Approach');
insert into products (product_name, price, description) values ('Steam Pan Full Lid', '80', 'High Dose Rate (HDR) Brachytherapy of Lung using Iridium 192');
insert into products (product_name, price, description) values ('Salmon - Top Butt Aaa', '40', 'Removal of Drainage Device from L Up Extrem, Extern Approach');
insert into products (product_name, price, description) values ('Carrots - Mini Red Organic', '1978', 'Repair Ampulla of Vater, Via Natural or Artificial Opening');
insert into products (product_name, price, description) values ('Snails - Large Canned', '1', 'High Dose Rate (HDR) Brachytherapy of Abd using Cesium 137');
insert into products (product_name, price, description) values ('Oil - Coconut', '51585', 'Replacement of Left Renal Vein with Autol Sub, Open Approach');
insert into products (product_name, price, description) values ('Table Cloth 144x90 White', '66856', 'Release Duodenum, Via Natural or Artificial Opening');
insert into products (product_name, price, description) values ('Pastrami', '32010', 'Removal of Spacer from Left Sacroiliac Joint, Open Approach');
insert into products (product_name, price, description) values ('Browning Caramel Glace', '5', 'Alteration of Chest Subcu/Fascia, Perc Approach');
insert into products (product_name, price, description) values ('Veal Inside - Provimi', '818', 'Dilation of Innom Art with 3 Intralum Dev, Open Approach');
insert into products (product_name, price, description) values ('Soup - Campbellschix Stew', '364', 'Bypass Cecum to Sigmoid Colon with Synth Sub, Endo');
insert into products (product_name, price, description) values ('Icecream Bar - Del Monte', '3142', 'Alteration of L Up Eyelid with Nonaut Sub, Open Approach');
insert into products (product_name, price, description) values ('Crab Brie In Phyllo', '66380', 'Insertion of Radioactive Element into L Knee, Perc Approach');
insert into products (product_name, price, description) values ('Pomegranates', '69480', 'Assistive Listening Device Device Fitting using AV Equipment');
insert into products (product_name, price, description) values ('Wine - Zinfandel California 2002', '28793', 'Excision of Right Common Iliac Vein, Perc Endo Approach');
insert into products (product_name, price, description) values ('Table Cloth 62x120 White', '7', 'Destruction of Lower Gingiva, Percutaneous Approach');
insert into products (product_name, price, description) values ('Pasta - Lasagna Dry', '3399', 'Insertion of Intralum Dev into Small Intest, Perc Approach');
insert into products (product_name, price, description) values ('Trout - Smoked', '943', 'Dilation of Left Foot Vein with Intralum Dev, Open Approach');
insert into products (product_name, price, description) values ('Tray - 16in Rnd Blk', '2', 'Resection of Thoracic Vertebral Disc, Open Approach');
insert into products (product_name, price, description) values ('Salmon Steak - Cohoe 6 Oz', '6', 'MRI of Corp Cavernosa using Oth Contrast, Unenh, Enhance');
insert into products (product_name, price, description) values ('Shichimi Togarashi Peppeers', '4', 'Replace Aort Valve w Nonaut Sub, Transap, Perc');
insert into products (product_name, price, description) values ('Wakami Seaweed', '1', 'Resection of Left Ureter, Percutaneous Endoscopic Approach');
insert into products (product_name, price, description) values ('Wine - Clavet Saint Emilion', '7', 'Bypass L Atrium to L Pulm Vn with Autol Art, Open Approach');
insert into products (product_name, price, description) values ('Nut - Pumpkin Seeds', '1844', 'Drainage of Left Occipital Bone, Perc Endo Approach');
insert into products (product_name, price, description) values ('Cumin - Ground', '67937', 'Insert Intralum Dev in L Basilic Vein, Perc Endo');
insert into products (product_name, price, description) values ('Island Oasis - Strawberry', '284', 'Excision of Upper Jaw, External Approach, Diagnostic');
insert into products (product_name, price, description) values ('Cake - Box Window 10x10x2.5', '269', 'Drainage of Right External Auditory Canal, Perc Approach');
insert into products (product_name, price, description) values ('Potatoes - Parissienne', '54', 'Supplement Cul-de-sac with Nonaut Sub, Open Approach');
insert into products (product_name, price, description) values ('Glass Clear 7 Oz Xl', '258', 'Drainage of Left Axillary Artery, Perc Endo Approach, Diagn');
insert into products (product_name, price, description) values ('Cocoa Powder - Dutched', '9', 'Repair Right Ureter, Percutaneous Endoscopic Approach');
insert into products (product_name, price, description) values ('Rosemary - Primerba Paste', '334', 'Reposition Lum Jt with Int Fix, Open Approach');
insert into products (product_name, price, description) values ('Capers - Ox Eye Daisy', '8', 'Drainage of Right Eustachian Tube, Endo');
insert into products (product_name, price, description) values ('Roe - White Fish', '343', 'Removal of Monitoring Device from Tracheobronc Tree, Endo');
insert into products (product_name, price, description) values ('Quiche Assorted', '7034', 'Destruction of Right Abdomen Muscle, Perc Endo Approach');
insert into products (product_name, price, description) values ('Vaccum Bag - 14x20', '6', 'Supplement R Zygomatic Bone w Nonaut Sub, Perc Endo');
insert into products (product_name, price, description) values ('Bread - Bistro White', '635', 'Reposition Ileum, Open Approach');
insert into products (product_name, price, description) values ('Wine - Red Gamay Noir', '6863', 'Supplement L Hand Bursa/Lig w Autol Sub, Perc Endo');
insert into products (product_name, price, description) values ('Gherkin', '6915', 'Revision of Int Fix in L Pelvic Bone, Perc Endo Approach');
insert into products (product_name, price, description) values ('Salt - Rock Course', '5', 'Revision of Monitoring Device in Low Intest Tract, Endo');
insert into products (product_name, price, description) values ('Milk 2% 500 Ml', '6658', 'Repair Right Tibia, Percutaneous Approach');
insert into products (product_name, price, description) values ('Bagel - Sesame Seed Presliced', '3', 'Change Drainage Device in Lower Bone, External Approach');
insert into products (product_name, price, description) values ('Cake - Cake Sheet Macaroon', '9994', 'Bypass Cereb Vent to Intestine with Synth Sub, Open Approach');
insert into products (product_name, price, description) values ('Dried Peach', '1', 'Excision of Left Metatarsal-Tarsal Joint, Perc Approach');
insert into products (product_name, price, description) values ('Juice - V8 Tomato', '100', 'Release Right Temporal Bone, Perc Endo Approach');
insert into products (product_name, price, description) values ('Coffee - Egg Nog Capuccino', '66854', 'Replacement of L Popl Art with Nonaut Sub, Open Approach');
insert into products (product_name, price, description) values ('Huck White Towels', '4156', 'Supplement L Abd Bursa/Lig w Synth Sub, Perc Endo');
insert into products (product_name, price, description) values ('Table Cloth 54x54 Colour', '9033', 'Beam Radiation of Thorax Lymphatics using Photons >10 MeV');
insert into products (product_name, price, description) values ('Sobe - Berry Energy', '4259', 'Restrict R Colic Art w Extralum Dev, Perc Endo');
insert into products (product_name, price, description) values ('Squid - U 5', '1597', 'Repair Right Finger Phalangeal Joint, External Approach');
insert into products (product_name, price, description) values ('Lentils - Green Le Puy', '99977', 'Monaural Hearing Aid Device Fitting using Hear Aid Equipment');
insert into products (product_name, price, description) values ('Cumin - Ground', '100', 'Restriction of Right Internal Mammary Artery, Perc Approach');
insert into products (product_name, price, description) values ('Cumin - Whole', '6', 'Release Right Knee Tendon, Open Approach');
insert into products (product_name, price, description) values ('Sweet Pea Sprouts', '9053', 'Supplement Right Lower Eyelid with Synth Sub, Open Approach');
insert into products (product_name, price, description) values ('Soup - Campbells - Chicken Noodle', '7', 'Bypass Cystic Duct to Right Hepatic Duct, Open Approach');
insert into products (product_name, price, description) values ('Radish - Black Winter Organic', '315', 'Excision of Vulva, Open Approach');
insert into products (product_name, price, description) values ('Wine - Vovray Sec Domaine Huet', '83559', 'Insertion of Infusion Device into Tracheobronc Tree, Endo');
insert into products (product_name, price, description) values ('Quiche Assorted', '2975', 'Bypass Bi Ureter to Bladder w Nonaut Sub, Perc Endo');
insert into products (product_name, price, description) values ('Pastry - Chocolate Chip Muffin', '7', 'Occlusion of Intracran Vein with Extralum Dev, Open Approach');
insert into products (product_name, price, description) values ('Breakfast Quesadillas', '3774', 'Extraction of Right Lesser Saphenous Vein, Perc Approach');
insert into products (product_name, price, description) values ('Bar Mix - Lemon', '829', 'Bypass Thor Aorta Asc to Pulm Trunk, Open Approach');
insert into products (product_name, price, description) values ('Cheese - Cheddar With Claret', '95366', 'Insertion of Int Fix into L Shoulder Jt, Perc Approach');
insert into products (product_name, price, description) values ('Tomatoes - Heirloom', '5273', 'Nonspoken Language Treatment using Computer');
insert into products (product_name, price, description) values ('Stock - Fish', '7681', 'Revision of Monitoring Device in Kidney, Open Approach');
insert into products (product_name, price, description) values ('Canadian Emmenthal', '3', 'Removal of Ext Fix from L Finger Phalanx Jt, Open Approach');
insert into products (product_name, price, description) values ('Puree - Guava', '86', 'Change Intermittent Pressure Device on Right Upper Extremity');
insert into products (product_name, price, description) values ('Tea - Jasmin Green', '4637', 'Excision of Right Large Intestine, Perc Endo Approach');
insert into products (product_name, price, description) values ('Soup - Campbells Chicken', '1874', 'Removal of Drainage Device from Lower Artery, Perc Approach');
insert into products (product_name, price, description) values ('Peas Snow', '369', 'Excision of Abdominal Wall, Percutaneous Approach');
insert into products (product_name, price, description) values ('Pepper - Cubanelle', '1', 'Replacement of L Pulm Vein with Nonaut Sub, Open Approach');
insert into products (product_name, price, description) values ('Limes', '24742', 'Release Pudendal Nerve, Percutaneous Approach');
insert into products (product_name, price, description) values ('Salmon Striploin Aaa', '9869', 'Remove Radioact Elem from Tracheobronc Tree, Open');
insert into products (product_name, price, description) values ('Shampoo - Blue', '2996', 'Inspection of Right Hip Joint, External Approach');
insert into products (product_name, price, description) values ('Cookies - Englishbay Wht', '4', 'Motor Functn Trmt Musculosk Head, Neck w Orthosis');
insert into products (product_name, price, description) values ('Sandwich Wrap', '2', 'Revision of Nonaut Sub in Up Vein, Perc Endo Approach');
insert into products (product_name, price, description) values ('Rosemary - Dry', '5', 'LDR Brachytherapy of Diaphragm using Californium 252');
insert into products (product_name, price, description) values ('Cocoa Powder - Natural', '8', 'Drainage of Right Upper Extremity Lymphatic, Perc Approach');
insert into products (product_name, price, description) values ('Shrimp - Black Tiger 16/20', '32389', 'Bypass Esophagus to Jejunum with Synth Sub, Open Approach');
insert into products (product_name, price, description) values ('Cheese - Brick With Pepper', '47', 'Drainage of Prostate, Open Approach');
insert into products (product_name, price, description) values ('Bacardi Mojito', '4842', 'Resection of Left Hip Muscle, Open Approach');
insert into products (product_name, price, description) values ('Soup - Campbells Chicken', '29632', 'Repair Bilateral Ovaries, Percutaneous Approach');
insert into products (product_name, price, description) values ('Chestnuts - Whole canned', '9', 'Extirpation of Matter from Left Conjunctiva, Extern Approach');
insert into products (product_name, price, description) values ('Jolt Cola - Red Eye', '3596', 'Fusion of C-thor Jt, Post Appr P Col, Open Approach');
insert into products (product_name, price, description) values ('Poppy Seed', '920', 'Removal of Nonaut Sub from L Elbow Jt, Open Approach');
insert into products (product_name, price, description) values ('Artichoke - Fresh', '1270', 'Revision of Nonaut Sub in Up Intest Tract, Perc Approach');
insert into products (product_name, price, description) values ('Macaroons - Two Bite Choc', '268', 'Dilation of Gastric Artery with 4 Drug-elut, Open Approach');
insert into products (product_name, price, description) values ('Mustard - Individual Pkg', '70', 'Bypass R Axilla Vein to Up Vein w Autol Vn, Perc Endo');
insert into products (product_name, price, description) values ('Vinegar - Cider', '5450', 'Revision of Int Fix in L Patella, Extern Approach');
insert into products (product_name, price, description) values ('Lettuce - Radicchio', '20255', 'CT Scan of L Renal Vein using L Osm Contrast');
insert into products (product_name, price, description) values ('Canadian Emmenthal', '2918', 'Occlusion L Ext Iliac Vein w Extralum Dev, Open');
insert into products (product_name, price, description) values ('Ranchero - Primerba Paste', '1780', 'Heart and Great Vessels, Restriction');
insert into products (product_name, price, description) values ('Snails - Large Canned', '5', 'Introduction of Other Gas into Periton Cav, Perc Approach');
insert into products (product_name, price, description) values ('Chips - Assorted', '6187', 'Reattachment of Ampulla of Vater, Perc Endo Approach');
insert into products (product_name, price, description) values ('Nut - Peanut Roasted', '30024', 'Excision of Hemorrhoidal Plexus, Percutaneous Approach');
insert into products (product_name, price, description) values ('Goat - Leg', '905', 'Insert Infusion Dev in L Int Carotid, Perc Endo');
insert into products (product_name, price, description) values ('Cheese - Augre Des Champs', '3819', 'Replacement of Left Scapula with Autol Sub, Open Approach');
insert into products (product_name, price, description) values ('Bread - Roll Soft White Round', '33', 'Restrict of L Int Iliac Art with Extralum Dev, Perc Approach');
insert into products (product_name, price, description) values ('Basil - Thai', '71990', 'Restriction of Right Lacrimal Duct, Open Approach');
insert into products (product_name, price, description) values ('Wine - Zonnebloem Pinotage', '7385', 'Excision of Gastric Artery, Percutaneous Approach');
insert into products (product_name, price, description) values ('Glycerine', '168', 'Revise of Infusion Dev in Fallopian Tube, Perc Endo Approach');
insert into products (product_name, price, description) values ('Fish - Loin Bone - In', '2', 'Dilate Hepatic Art, Bifurc, w 2 Intralum Dev, Perc Endo');
insert into products (product_name, price, description) values ('Cups 10oz Trans', '1413', 'Drain of R Low Leg Tendon with Drain Dev, Perc Endo Approach');
insert into products (product_name, price, description) values ('Butter Balls Salted', '45425', 'Destruction of Right Mandible, Open Approach');
insert into products (product_name, price, description) values ('Pasta - Orzo Dry', '7', 'Removal of Drainage Device from T-lum Jt, Extern Approach');
insert into products (product_name, price, description) values ('Fish Casing', '40285', 'Dilation of Sup Mesent Art with 2 Drug-elut, Perc Approach');
insert into products (product_name, price, description) values ('Shampoo - Camerons Cream Ale', '612', 'Reposition Products of Conception, Via Opening');
insert into products (product_name, price, description) values ('Pear - Halves', '4', 'Revise of Autol Sub in Epididymis/Sperm Cord, Perc Approach');
insert into products (product_name, price, description) values ('Salad Dressing', '1957', 'Occlusion of Lower Esophagus, Via Opening');
insert into products (product_name, price, description) values ('Cornish Hen', '53061', 'Repair Right Parotid Duct, Percutaneous Approach');
insert into products (product_name, price, description) values ('Raisin - Dark', '214', 'Supplement Right Index Finger with Autol Sub, Open Approach');
insert into products (product_name, price, description) values ('Ecolab - Ster Bac', '879', 'Bypass Innom Art to L Low Arm Art w Autol Art, Open');
insert into products (product_name, price, description) values ('Pear - Asian', '54420', 'Dilate L Thyroid Art, Bifurc, w 3 Intralum Dev, Perc');
insert into products (product_name, price, description) values ('Apron', '10725', 'Extirpation of Matter from Mesenteric Lymph, Open Approach');
insert into products (product_name, price, description) values ('Grenadillo', '120', 'Occlusion L Face Vein w Intralum Dev, Perc Endo');
insert into products (product_name, price, description) values ('Sugar - Individual Portions', '625', 'Excision of Right Abdomen Muscle, Open Approach');
insert into products (product_name, price, description) values ('Pasta - Detalini White Fresh', '5', 'Excision of Parathyroid Gland, Percutaneous Approach, Diagn');
insert into products (product_name, price, description) values ('Mint - Fresh', '23', 'Stereotactic Gamma Beam Radiosurgery of Rectum');
insert into products (product_name, price, description) values ('Hipnotiq Liquor', '6834', 'Drainage of Superior Mesenteric Vein, Perc Endo Approach');
insert into products (product_name, price, description) values ('Wine - Remy Pannier Rose', '79', 'Replacement of Splenic Vein with Nonaut Sub, Open Approach');
insert into products (product_name, price, description) values ('Glucose', '67', 'HDR Brachytherapy of Bronchus using Iridium 192');
insert into products (product_name, price, description) values ('RootShampoo', '9635', 'Bypass Sup Vena Cava to R Pulm Art w Zooplastic, Open');
insert into products (product_name, price, description) values ('Filter - Coffee', '464', 'Revision of Int Fix in L Carpal Jt, Perc Endo Approach');
insert into products (product_name, price, description) values ('Fish - Bacon Sliced', '209', 'Excision of Right External Ear, Open Approach');
insert into products (product_name, price, description) values ('Tart Shells - Sweet, 4', '850', 'Removal of Drainage Device from Lower Tendon, Perc Approach');
insert into products (product_name, price, description) values ('Artichokes - Jerusalem', '265', 'Reposition Right Tarsal Joint, Open Approach');
insert into products (product_name, price, description) values ('Juice - Ocean Spray Kiwi', '88921', 'Drainage of Left Neck Muscle, Perc Endo Approach, Diagn');
insert into products (product_name, price, description) values ('Muffin - Blueberry Individual', '33439', 'Supplement L Ext Jugular Vein with Nonaut Sub, Open Approach');
insert into products (product_name, price, description) values ('Cilantro / Coriander - Fresh', '66', 'Release Multiple Parathyroid Glands, Percutaneous Approach');
insert into products (product_name, price, description) values ('Water - Evian 355 Ml', '813', 'Introduce Oth Antineoplastic in Periph Art, Perc');
insert into products (product_name, price, description) values ('Pepper - Green', '1653', 'Revision of Spacer in R Metatarsophal Jt, Extern Approach');
insert into products (product_name, price, description) values ('Water - Aquafina Vitamin', '53475', 'Removal of Synth Sub from T-lum Jt, Perc Endo Approach');
insert into products (product_name, price, description) values ('Beans - Wax', '2', 'Destruction of Trachea, Via Natural or Artificial Opening');
insert into products (product_name, price, description) values ('Fish - Caul Fat', '17', 'Insertion of Monitor Dev into Small Intest, Open Approach');
insert into products (product_name, price, description) values ('Petit Baguette', '13', 'Excision of Abdominal Aorta, Perc Endo Approach, Diagn');
insert into products (product_name, price, description) values ('Artichokes - Jerusalem', '32', 'Measurement of Arterial Pressure, Peripheral, Open Approach');
insert into products (product_name, price, description) values ('Glass - Plastic Clear 5 Oz', '972', 'Extirpation of Matter from Upper Vein, Open Approach');
insert into products (product_name, price, description) values ('Sour Puss Raspberry', '1', 'Removal of Other Device from Resp Tract, Perc Approach');
insert into products (product_name, price, description) values ('Water - Spring Water 500ml', '3818', 'Revision of Nonautologous Tissue Substitute in L Ear, Endo');
insert into products (product_name, price, description) values ('The Pop Shoppe - Lime Rickey', '18488', 'Insertion of Pace Lead into Pericardium, Perc Endo Approach');
insert into products (product_name, price, description) values ('Water Chestnut - Canned', '74506', 'Supplement Trachea with Nonaut Sub, Open Approach');
insert into products (product_name, price, description) values ('Soup - Salmon Conomme Dry', '2', 'Release Left Basilic Vein, Percutaneous Endoscopic Approach');
insert into products (product_name, price, description) values ('Rice Pilaf- Drypackage', '9181', 'Reposition Left Glenoid Cavity, External Approach');
insert into products (product_name, price, description) values ('Basil - Fresh', '53267', 'Drainage of Bilateral Vas Deferens, Perc Approach, Diagn');
