INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Phone', 599, 'Smartphone with high-resolution display', 'Electronics', 100);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Laptop', 999, 'Lightweight and powerful laptop for professionals', 'Electronics', 150);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Headphones', 99, 'Wireless over-ear headphones with noise cancellation', 'Electronics', 200);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smartwatch', 199, 'Fitness tracker and smartwatch with heart rate monitor', 'Electronics', 80);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Tablet', 349, '10-inch tablet with a powerful processor', 'Electronics', 120);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Gaming Mouse', 49, 'High-precision gaming mouse with customizable buttons', 'Electronics', 250);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Keyboard', 79, 'Ergonomic wireless keyboard for comfortable typing', 'Electronics', 180);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('External Hard Drive', 129, '1TB portable external hard drive for data storage', 'Electronics', 90);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Camera', 499, 'Mirrorless camera with 4K video recording', 'Electronics', 70);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Printer', 159, 'Color inkjet printer with wireless connectivity', 'Electronics', 110);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('TV', 699, '55-inch 4K smart TV with built-in streaming apps', 'Electronics', 50);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Blender', 79, 'High-powered blender for smoothies and food processing', 'Kitchen Appliances', 100);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Refrigerator', 899, 'Stainless steel French door refrigerator', 'Appliances', 30);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Vacuum Cleaner', 199, 'Bagless vacuum cleaner with strong suction power', 'Appliances', 70);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Coffee Maker', 49, 'Programmable coffee maker with a built-in grinder', 'Kitchen Appliances', 120);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Toaster', 29, '2-slice stainless steel toaster', 'Kitchen Appliances', 90);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Microwave', 149, 'Countertop microwave oven with defrost function', 'Appliances', 80);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Water Bottle', 19, 'BPA-free reusable water bottle', 'Kitchen & Dining', 200);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Fitness Tracker', 79, 'Smart fitness tracker with heart rate and sleep monitoring', 'Electronics', 160);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Power Bank', 39, 'Portable power bank for charging devices on the go', 'Electronics', 250);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Earbuds', 129, 'True wireless earbuds with noise isolation', 'Electronics', 100);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Portable Speaker', 89, 'Bluetooth portable speaker with waterproof design', 'Electronics', 120);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Backpack', 59, 'Durable backpack with multiple compartments', 'Fashion', 200);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Gaming Console', 299, 'Latest gaming console with high-performance graphics', 'Electronics', 60);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('External SSD', 199, '500GB external solid-state drive for fast data transfer', 'Electronics', 90);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Router', 79, 'High-speed wireless router with wide coverage', 'Electronics', 100);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Bluetooth Headset', 69, 'Comfortable Bluetooth headset with long battery life', 'Electronics', 150);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('HDMI Cable', 9, 'High-speed HDMI cable for 4K video', 'Electronics', 300);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Bulb', 19, 'Wi-Fi-enabled smart bulb with color changing options', 'Electronics', 180);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Robot Vacuum', 349, 'Robotic vacuum cleaner with smart mapping technology', 'Appliances', 40);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Air Purifier', 199, 'HEPA air purifier for allergies and dust removal', 'Appliances', 60);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Security Camera', 129, 'Outdoor security camera with night vision', 'Electronics', 90);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Charger', 39, 'Qi wireless charger for compatible devices', 'Electronics', 150);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Thermostat', 149, 'Wi-Fi-enabled smart thermostat for home automation', 'Home Improvement', 70);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Electric Toothbrush', 79, 'Rechargeable electric toothbrush with multiple modes', 'Personal Care', 120);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Baby Monitor', 89, 'Video baby monitor with night vision and two-way audio', 'Baby & Kids', 100);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Fitness Equipment', 249, 'Home gym equipment for full-body workouts', 'Sports & Outdoors', 50);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Bluetooth Keyboard', 69, 'Compact Bluetooth keyboard for tablets and smartphones', 'Electronics', 120);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Mouse', 29, 'Optical wireless mouse for laptops and desktops', 'Electronics', 200);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Cookware Set', 199, 'Stainless steel cookware set with non-stick coating', 'Kitchen & Dining', 80);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Portable Monitor', 199, '15.6-inch portable monitor with USB-C connectivity', 'Electronics', 70);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Electric Kettle', 49, 'Fast-boiling electric kettle with auto shut-off', 'Kitchen Appliances', 150);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Indoor Plant', 29, 'Low-maintenance indoor plant for home decor', 'Home & Garden', 250);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Gaming Controller', 59, 'Bluetooth gaming controller for consoles and PC', 'Electronics', 100);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Digital Scale', 19, 'Digital kitchen scale for precise measurements', 'Kitchen & Dining', 180);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Cordless Drill', 79, 'Cordless power drill with rechargeable batteries', 'Tools & Home Improvement', 120);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Dumbbell Set', 79, 'Adjustable dumbbell set for home workouts', 'Sports & Outdoors', 80);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Bluetooth Speaker', 49, 'Portable Bluetooth speaker with stereo sound', 'Electronics', 150);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Cordless Vacuum', 169, 'Lightweight cordless vacuum cleaner with strong suction', 'Appliances', 90);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Video Doorbell', 199, 'Smart video doorbell with two-way audio', 'Electronics', 60);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Security System', 349, 'Wireless home security system with cameras and sensors', 'Electronics', 40);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Earphones', 79, 'Wireless earphones with noise-canceling technology', 'Electronics', 120);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart TV', 799, '65-inch 4K smart TV with voice control', 'Electronics', 50);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Gaming Headset', 129, 'Gaming headset with surround sound and RGB lighting', 'Electronics', 80);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Bluetooth Fitness Earbuds', 99, 'Water-resistant fitness earbuds with heart rate monitoring', 'Electronics', 110);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Robot Lawn Mower', 599, 'Automated lawn mower for maintaining the lawn', 'Tools & Home Improvement', 30);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Air Fryer', 89, 'Oil-less air fryer for healthier cooking', 'Kitchen Appliances', 70);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Plug', 19, 'Wi-Fi-enabled smart plug for home automation', 'Electronics', 150);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Portable Projector', 249, 'Mini portable projector for home entertainment', 'Electronics', 90);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Bluetooth Car Kit', 39, 'Hands-free Bluetooth car kit for safer driving', 'Automotive', 100);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Gaming Mouse', 59, 'High-precision wireless gaming mouse', 'Electronics', 200);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Lock', 149, 'Keyless smart lock with smartphone control', 'Home Improvement', 80);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Noise-Canceling Headphones', 199, 'Over-ear headphones with active noise cancellation', 'Electronics', 70);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Juicer', 69, 'Electric citrus juicer for fresh juice', 'Kitchen Appliances', 110);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Drone', 399, 'Camera drone with 4K video and GPS tracking', 'Electronics', 40);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Cordless Handheld Vacuum', 79, 'Portable cordless handheld vacuum cleaner', 'Appliances', 80);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('AirPods Case', 29, 'Protective case for Apple AirPods', 'Electronics', 250);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Charging Pad', 29, 'Fast wireless charging pad for smartphones', 'Electronics', 200);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Fitness Foam Roller', 29, 'High-density foam roller for muscle recovery', 'Sports & Outdoors', 150);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Yoga Mat', 39, 'Non-slip yoga mat for home workouts', 'Sports & Outdoors', 180);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Electric Scooter', 299, 'Foldable electric scooter for short commutes', 'Outdoor Recreation', 70);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('LED Desk Lamp', 49, 'Adjustable LED desk lamp with USB charging port', 'Home Improvement', 120);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Home Security Camera', 129, 'Indoor smart home security camera with motion detection', 'Electronics', 80);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Bluetooth Shower Speaker', 24, 'Waterproof Bluetooth speaker for shower use', 'Electronics', 250);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Sport Earphones', 49, 'Sweatproof wireless earphones for sports', 'Electronics', 100);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Robot Vacuum with Mop', 349, 'Robotic vacuum with mopping function', 'Appliances', 60);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Charging Stand', 39, 'Charging stand for smartphones and smartwatches', 'Electronics', 150);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Electric Bike', 799, 'Electric-assisted bicycle for urban commuting', 'Outdoor Recreation', 40);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Cordless Water Flosser', 59, 'Portable water flosser for oral hygiene', 'Personal Care', 90);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Home Hub', 89, 'Central hub for controlling smart home devices', 'Electronics', 100);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Fitness Tracker with GPS', 129, 'GPS-enabled fitness tracker for outdoor activities', 'Electronics', 70);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Mini Projector', 179, 'Compact mini projector for presentations and movies', 'Electronics', 80);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Portable Bluetooth Keyboard', 39, 'Foldable Bluetooth keyboard for smartphones and tablets', 'Electronics', 150);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Portable Power Station', 299, 'High-capacity portable power station for camping', 'Electronics', 60);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Bluetooth FM Transmitter', 19, 'Wireless FM transmitter for car audio', 'Electronics', 120);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Charging Mouse Pad', 29, 'Mouse pad with integrated wireless charger', 'Electronics', 200);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Stainless Steel Water Bottle', 19, 'Insulated stainless steel water bottle', 'Kitchen & Dining', 180);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Bluetooth Karaoke Microphone', 39, 'Wireless karaoke microphone with built-in speaker', 'Electronics', 100);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Ceiling Fan', 149, 'Wi-Fi-enabled ceiling fan with remote control', 'Home Improvement', 80);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('LED Strip Lights', 29, 'RGB LED strip lights with remote control', 'Electronics', 120);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Portable Laptop Stand', 24, 'Adjustable laptop stand for better ergonomics', 'Electronics', 200);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Handheld Milk Frother', 19, 'Battery-operated milk frother for coffee drinks', 'Kitchen Appliances', 150);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('LED Bike Lights', 14, 'USB-rechargeable LED lights for bicycles', 'Outdoor Recreation', 250);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Door Lock', 199, 'Keyless smart door lock with touchpad', 'Home Improvement', 100);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Backup Camera', 49, 'Wireless rearview backup camera for vehicles', 'Automotive', 70);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Fitness Resistance Bands', 29, 'Set of resistance bands for home workouts', 'Sports & Outdoors', 120);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Portable Clothes Steamer', 39, 'Travel-sized clothes steamer for wrinkle-free garments', 'Home & Garden', 150);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Solar Power Bank', 49, 'Solar-powered portable power bank', 'Electronics', 80);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Water Leak Detector', 29, 'Wi-Fi-enabled water leak sensor for home safety', 'Home Improvement', 100);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Cord Organizer', 14, 'Cable management organizer for desk or travel', 'Electronics', 200);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Remote Control Outlet', 19, 'Remote-controlled electrical outlets for home automation', 'Home Appliances', 50);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Coffee Maker', 89, 'Wi-Fi-enabled coffee maker with app control', 'Home Appliances', 32);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Portable Air Conditioner', 299, 'Mobile air conditioner for cooling small spaces', 'Home Appliances', 20);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Pet Feeder', 79, 'Automatic pet feeder with scheduling and portion control', 'Pet Supplies', 45);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Earbuds with Mic', 49, 'Wireless earbuds with built-in microphone', 'Electronics', 80);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Fitness Tracker Watch', 69, 'Multi-function fitness watch with heart rate monitor', 'Electronics', 55);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Mini Wi-Fi Camera', 39, 'Compact Wi-Fi camera for home monitoring', 'Electronics', 60);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Gaming Keyboard', 69, 'Mechanical gaming keyboard with RGB lighting', 'Electronics', 75);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart LED Bulb', 19, 'Wi-Fi-enabled LED bulb with voice control', 'Home Appliances', 90);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Charging Car Mount', 39, 'Car mount with wireless charging for smartphones', 'Electronics', 40);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Light Switch', 29, 'Wi-Fi-enabled light switch for home automation', 'Home Improvement', 65);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Electric Griddle', 49, 'Large electric griddle for cooking breakfast foods', 'Home Appliances', 25);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Portable Bluetooth Speaker', 29, 'Compact and portable Bluetooth speaker', 'Electronics', 30);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Window Blinds', 99, 'Automated window blinds with remote control', 'Home Improvement', 15);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Digital Meat Thermometer', 19, 'Instant-read digital meat thermometer', 'Kitchen Utensils', 70);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Water Bottle', 29, 'Water bottle with hydration reminder and app integration', 'Fitness & Sports', 50);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Mini Air Purifier', 49, 'Desktop air purifier for personal use', 'Home Appliances', 28);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Gaming Headset Stand', 19, 'Headset stand with RGB lighting for gamers', 'Electronics', 80);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Desk Lamp', 39, 'Adjustable desk lamp with color temperature control', 'Home Improvement', 35);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Charging Pad for Apple Watch', 29, 'Charging pad for wirelessly charging Apple Watch', 'Electronics', 60);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Electric Pressure Cooker', 79, 'Multi-function electric pressure cooker', 'Kitchen Appliances', 42);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Wi-Fi Plug', 19, 'Wi-Fi-enabled smart plug with energy monitoring', 'Home Automation', 95);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('USB-C Hub', 29, 'Multi-port USB-C hub for laptops and devices', 'Electronics', 70);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Touchpad Keyboard', 49, 'Keyboard with built-in touchpad for smart TVs', 'Electronics', 60);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Robot Window Cleaner', 149, 'Automated window cleaning robot', 'Home Appliances', 18);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Collapsible Silicone Food Storage Containers', 29, 'Set of space-saving food containers', 'Kitchen Utensils', 65);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Garage Door Opener', 129, 'Wi-Fi-enabled garage door opener with remote control', 'Home Improvement', 22);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('LED Camping Lantern', 24, 'Portable LED lantern for camping and emergencies', 'Outdoor & Recreation', 40);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Baby Monitor', 99, 'Wi-Fi-enabled baby monitor with camera and app', 'Baby & Kids', 30);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Portable Espresso Maker', 49, 'Handheld espresso maker for coffee on the go', 'Kitchen Appliances', 55);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Gaming Controller Charging Station', 19, 'Charging dock for gaming controllers', 'Electronics', 70);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Plant Watering Kit', 39, 'Automated plant watering system with sensors', 'Gardening', 35);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Mini Portable Fan', 14, 'USB-powered mini fan for personal cooling', 'Home Appliances', 80);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Bluetooth Gamepad for Mobile Phones', 29, 'Wireless gamepad for mobile gaming', 'Electronics', 50);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Automatic Soap Dispenser', 19, 'Touchless soap dispenser for improved hygiene', 'Home Appliances', 90);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Wi-Fi Router', 69, 'High-speed Wi-Fi router with parental controls', 'Electronics', 40);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('USB Desk Fan', 19, 'Quiet USB-powered fan for office use', 'Electronics', 50);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Car Charger', 29, 'Qi wireless charger for car use', 'Electronics', 40);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Watering Timer', 29, 'Automated watering timer for garden irrigation', 'Home Improvement', 30);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Folding Bluetooth Keyboard for Smartphones', 49, 'Compact folding keyboard for smartphones', 'Electronics', 65);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Wi-Fi Doorbell', 89, 'Video doorbell with motion detection and cloud storage', 'Home Improvement', 25);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Fitness Balance Board', 39, 'Balance board for core and stability training', 'Fitness Accessories', 40);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Mini Portable Projector Screen', 49, 'Collapsible projector screen for presentations', 'Electronics', 15);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Car Phone Mount', 14, 'Universal phone mount for car dashboard', 'Car Accessories', 60);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Light Bulbs Starter Kit', 79, 'Set of smart light bulbs with hub', 'Home Improvement', 35);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Backup External Hard Drive', 149, 'Portable external hard drive with automatic backup', 'Electronics', 20);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Wi-Fi Humidifier', 59, 'Wi-Fi-enabled humidifier with adjustable mist levels', 'Home Appliances', 48);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Portable UV Sanitizer', 24, 'UV sanitizer for disinfecting small items', 'Home Appliances', 55);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Window Curtains', 99, 'Automated window curtains with remote control', 'Home Improvement', 22);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Portable Laptop Desk', 29, 'Foldable laptop desk for comfortable computing', 'Home Office', 40);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Electric Bug Zapper', 39, 'Indoor and outdoor bug zapper with UV light', 'Home Improvement', 30);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart RGB Light Strip', 29, 'Wi-Fi-enabled RGB light strip with music sync', 'Electronics', 40);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Wi-Fi Thermostat', 129, 'Programmable thermostat with app control', 'Home Improvement', 25);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Gaming Controller', 49, 'Bluetooth gaming controller for consoles and PC', 'Electronics', 60);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Water Leak Sensor', 19, 'Wireless water leak detector for home protection', 'Home Security', 35);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Portable Bluetooth Keyboard for Tablets', 39, 'Slim and portable keyboard for tablets', 'Electronics', 45);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Touchpad Mouse', 29, 'Multi-touch wireless mouse for laptops', 'Computer Accessories', 55);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Mini HD Action Camera', 79, 'Compact action camera for recording adventures', 'Electronics', 20);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Wi-Fi Socket', 24, 'Wi-Fi-enabled smart socket with energy monitoring', 'Home Automation', 50);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Portable Neck Fan', 19, 'Hands-free neck fan for outdoor activities', 'Personal Care', 30);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Home Weather Station', 69, 'Wireless weather station with indoor and outdoor sensors', 'Home Automation', 22);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Cordless Electric Kettle', 39, 'Rapid-boil cordless kettle for hot beverages', 'Kitchen Appliances', 40);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Plant Monitor', 29, 'Sensor-based plant monitor with app notifications', 'Garden', 35);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Fitness Exercise Ball', 19, 'Anti-burst exercise ball for workouts', 'Fitness Accessories', 60);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Portable Wireless Mouse', 24, 'Compact wireless mouse for travel', 'Computer Accessories', 50);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Wi-Fi Light Switch', 29, 'Wi-Fi-enabled light switch with voice control', 'Home Automation', 30);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('USB-Powered Desk Heater', 29, 'Mini desktop heater for personal warmth', 'Home Appliances', 25);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Wi-Fi Security Camera', 49, 'Indoor and outdoor security camera with cloud storage', 'Home Security', 40);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Yoga Blocks', 19, 'Set of yoga blocks for support and stability', 'Fitness Accessories', 30);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Bluetooth Ear Muffs', 39, 'Bluetooth ear muffs with built-in speakers', 'Electronics', 45);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Home Door Sensor', 19, 'Wireless door sensor for home security', 'Home Security', 50);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Bluetooth Beanie', 24, 'Knit beanie with built-in wireless headphones', 'Electronics', 35);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Portable Air Compressor', 59, 'Compact air compressor for inflating tires and sports equipment', 'Automotive', 20);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Drawer Organizer', 39, 'Electronic drawer organizer with app control', 'Home Improvement', 22);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('LED Bike Helmet', 49, 'Bicycle helmet with integrated LED lights', 'Sports & Outdoors', 40);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Wi-Fi Water Pitcher', 29, 'Wi-Fi-enabled water pitcher with filter status tracking', 'Kitchen Appliances', 30);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Bluetooth Car Adapter', 19, 'Bluetooth adapter for car audio systems', 'Car Accessories', 55);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Air Purifier', 129, 'Wi-Fi-enabled air purifier with air quality monitoring', 'Home Appliances', 18);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Travel Neck Pillow', 19, 'Memory foam neck pillow for travel comfort', 'Travel Accessories', 25);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Pet Tracker', 49, 'GPS pet tracker with activity monitoring', 'Pets', 30);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Gaming Mouse Pad', 14, 'Large mouse pad optimized for gaming', 'Computer Accessories', 40);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Wi-Fi Power Strip', 39, 'Wi-Fi-enabled power strip with individual outlets control', 'Home Automation', 25);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Mini Bluetooth Printer', 79, 'Portable Bluetooth printer for mobile printing', 'Electronics', 60);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Charging Desk Organizer', 49, 'Desktop organizer with integrated wireless charger', 'Home Accessories', 35);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Watering Can', 29, 'Automatic watering can with precise pouring', 'Garden', 45);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Bluetooth Remote Shutter', 14, 'Remote shutter for smartphone photography', 'Electronics', 55);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Wi-Fi Air Fryer', 99, 'Wi-Fi-enabled air fryer with recipe app', 'Kitchen Appliances', 20);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Portable Handheld Fan', 19, 'Mini handheld fan with adjustable speed', 'Personal Care', 22);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Voice Translator', 69, 'Language translator with voice recognition', 'Electronics', 40);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Wireless Bluetooth FM Radio', 29, 'Bluetooth FM radio with SD card support', 'Electronics', 35);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Doorbell Camera', 89, 'Video doorbell with motion detection and two-way audio', 'Home Security', 50);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Portable LED Work Light', 24, 'Rechargeable LED work light for projects', 'Home Improvement', 22);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Pet Water Fountain', 49, 'Wi-Fi-enabled water fountain for pets', 'Pets', 40);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Cordless Handheld Fan', 14, 'Handheld fan with USB rechargeability', 'Personal Care', 30);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('LED Desk Clock', 29, 'Desk clock with adjustable LED display', 'Home Accessories', 25);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Wi-Fi Vacuum Sealer', 79, 'Vacuum sealer with app control for food preservation', 'Kitchen Appliances', 40);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Portable Folding Camping Table', 39, 'Compact folding table for outdoor use', 'Outdoor Furniture', 35);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Night Light', 19, 'Motion-activated night light with color changing', 'Home Accessories', 55);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Mini Wireless Keyboard with Touchpad', 29, 'Compact wireless keyboard with touchpad', 'Computer Accessories', 30);
INSERT INTO products (name, price, description, category, stock_quantity) VALUES ('Smart Plant Pot', 39, 'Self-watering plant pot with app monitoring', 'Garden', 45);