INSERT INTO products (name, price, description) VALUES ('Phone', 599, 'Smartphone with high-resolution display');
INSERT INTO products (name, price, description) VALUES ('Laptop', 999, 'Lightweight and powerful laptop for professionals');
INSERT INTO products (name, price, description) VALUES ('Headphones', 99, 'Wireless over-ear headphones with noise cancellation');
INSERT INTO products (name, price, description) VALUES ('Smartwatch', 199, 'Fitness tracker and smartwatch with heart rate monitor');
INSERT INTO products (name, price, description) VALUES ('Tablet', 349, '10-inch tablet with a powerful processor');
INSERT INTO products (name, price, description) VALUES ('Gaming Mouse', 49, 'High-precision gaming mouse with customizable buttons');
INSERT INTO products (name, price, description) VALUES ('Wireless Keyboard', 79, 'Ergonomic wireless keyboard for comfortable typing');
INSERT INTO products (name, price, description) VALUES ('External Hard Drive', 129, '1TB portable external hard drive for data storage');
INSERT INTO products (name, price, description) VALUES ('Camera', 499, 'Mirrorless camera with 4K video recording');
INSERT INTO products (name, price, description) VALUES ('Printer', 159, 'Color inkjet printer with wireless connectivity');
INSERT INTO products (name, price, description) VALUES ('TV', 699, '55-inch 4K smart TV with built-in streaming apps');
INSERT INTO products (name, price, description) VALUES ('Blender', 79, 'High-powered blender for smoothies and food processing');
INSERT INTO products (name, price, description) VALUES ('Refrigerator', 899, 'Stainless steel French door refrigerator');
INSERT INTO products (name, price, description) VALUES ('Vacuum Cleaner', 199, 'Bagless vacuum cleaner with strong suction power');
INSERT INTO products (name, price, description) VALUES ('Coffee Maker', 49, 'Programmable coffee maker with a built-in grinder');
INSERT INTO products (name, price, description) VALUES ('Toaster', 29, '2-slice stainless steel toaster');
INSERT INTO products (name, price, description) VALUES ('Microwave', 149, 'Countertop microwave oven with defrost function');
INSERT INTO products (name, price, description) VALUES ('Water Bottle', 19, 'BPA-free reusable water bottle');
INSERT INTO products (name, price, description) VALUES ('Fitness Tracker', 79, 'Smart fitness tracker with heart rate and sleep monitoring');
INSERT INTO products (name, price, description) VALUES ('Power Bank', 39, 'Portable power bank for charging devices on the go');
INSERT INTO products (name, price, description) VALUES ('Wireless Earbuds', 129, 'True wireless earbuds with noise isolation');
INSERT INTO products (name, price, description) VALUES ('Portable Speaker', 89, 'Bluetooth portable speaker with waterproof design');
INSERT INTO products (name, price, description) VALUES ('Backpack', 59, 'Durable backpack with multiple compartments');
INSERT INTO products (name, price, description) VALUES ('Gaming Console', 299, 'Latest gaming console with high-performance graphics');
INSERT INTO products (name, price, description) VALUES ('External SSD', 199, '500GB external solid-state drive for fast data transfer');
INSERT INTO products (name, price, description) VALUES ('Wireless Router', 79, 'High-speed wireless router with wide coverage');
INSERT INTO products (name, price, description) VALUES ('Bluetooth Headset', 69, 'Comfortable Bluetooth headset with long battery life');
INSERT INTO products (name, price, description) VALUES ('HDMI Cable', 9, 'High-speed HDMI cable for 4K video');
INSERT INTO products (name, price, description) VALUES ('Smart Bulb', 19, 'Wi-Fi-enabled smart bulb with color changing options');
INSERT INTO products (name, price, description) VALUES ('Robot Vacuum', 349, 'Robotic vacuum cleaner with smart mapping technology');
INSERT INTO products (name, price, description) VALUES ('Air Purifier', 199, 'HEPA air purifier for allergies and dust removal');
INSERT INTO products (name, price, description) VALUES ('Security Camera', 129, 'Outdoor security camera with night vision');
INSERT INTO products (name, price, description) VALUES ('Wireless Charger', 39, 'Qi wireless charger for compatible devices');
INSERT INTO products (name, price, description) VALUES ('Smart Thermostat', 149, 'Wi-Fi-enabled smart thermostat for home automation');
INSERT INTO products (name, price, description) VALUES ('Electric Toothbrush', 79, 'Rechargeable electric toothbrush with multiple modes');
INSERT INTO products (name, price, description) VALUES ('Baby Monitor', 89, 'Video baby monitor with night vision and two-way audio');
INSERT INTO products (name, price, description) VALUES ('Fitness Equipment', 249, 'Home gym equipment for full-body workouts');
INSERT INTO products (name, price, description) VALUES ('Bluetooth Keyboard', 69, 'Compact Bluetooth keyboard for tablets and smartphones');
INSERT INTO products (name, price, description) VALUES ('Wireless Mouse', 29, 'Optical wireless mouse for laptops and desktops');
INSERT INTO products (name, price, description) VALUES ('Cookware Set', 199, 'Stainless steel cookware set with non-stick coating');
INSERT INTO products (name, price, description) VALUES ('Portable Monitor', 199, '15.6-inch portable monitor with USB-C connectivity');
INSERT INTO products (name, price, description) VALUES ('Electric Kettle', 49, 'Fast-boiling electric kettle with auto shut-off');
INSERT INTO products (name, price, description) VALUES ('Indoor Plant', 29, 'Low-maintenance indoor plant for home decor');
INSERT INTO products (name, price, description) VALUES ('Wireless Gaming Controller', 59, 'Bluetooth gaming controller for consoles and PC');
INSERT INTO products (name, price, description) VALUES ('Digital Scale', 19, 'Digital kitchen scale for precise measurements');
INSERT INTO products (name, price, description) VALUES ('Cordless Drill', 79, 'Cordless power drill with rechargeable batteries');
INSERT INTO products (name, price, description) VALUES ('Dumbbell Set', 79, 'Adjustable dumbbell set for home workouts');
INSERT INTO products (name, price, description) VALUES ('Bluetooth Speaker', 49, 'Portable Bluetooth speaker with stereo sound');
INSERT INTO products (name, price, description) VALUES ('Cordless Vacuum', 169, 'Lightweight cordless vacuum cleaner with strong suction');
INSERT INTO products (name, price, description) VALUES ('Video Doorbell', 199, 'Smart video doorbell with two-way audio');
INSERT INTO products (name, price, description) VALUES ('Wireless Security System', 349, 'Wireless home security system with cameras and sensors');
INSERT INTO products (name, price, description) VALUES ('Wireless Earphones', 79, 'Wireless earphones with noise-canceling technology');
INSERT INTO products (name, price, description) VALUES ('Smart TV', 799, '65-inch 4K smart TV with voice control');
INSERT INTO products (name, price, description) VALUES ('Wireless Gaming Headset', 129, 'Gaming headset with surround sound and RGB lighting');
INSERT INTO products (name, price, description) VALUES ('Bluetooth Fitness Earbuds', 99, 'Water-resistant fitness earbuds with heart rate monitoring');
INSERT INTO products (name, price, description) VALUES ('Robot Lawn Mower', 599, 'Automated lawn mower for maintaining the lawn');
INSERT INTO products (name, price, description) VALUES ('Air Fryer', 89, 'Oil-less air fryer for healthier cooking');
INSERT INTO products (name, price, description) VALUES ('Smart Plug', 19, 'Wi-Fi-enabled smart plug for home automation');
INSERT INTO products (name, price, description) VALUES ('Portable Projector', 249, 'Mini portable projector for home entertainment');
INSERT INTO products (name, price, description) VALUES ('Bluetooth Car Kit', 39, 'Hands-free Bluetooth car kit for safer driving');
INSERT INTO products (name, price, description) VALUES ('Wireless Gaming Mouse', 59, 'High-precision wireless gaming mouse');
INSERT INTO products (name, price, description) VALUES ('Smart Lock', 149, 'Keyless smart lock with smartphone control');
INSERT INTO products (name, price, description) VALUES ('Wireless Noise-Canceling Headphones', 199, 'Over-ear headphones with active noise cancellation');
INSERT INTO products (name, price, description) VALUES ('Juicer', 69, 'Electric citrus juicer for fresh juice');
INSERT INTO products (name, price, description) VALUES ('Drone', 399, 'Camera drone with 4K video and GPS tracking');
INSERT INTO products (name, price, description) VALUES ('Cordless Handheld Vacuum', 79, 'Portable cordless handheld vacuum cleaner');
INSERT INTO products (name, price, description) VALUES ('AirPods Case', 29, 'Protective case for Apple AirPods');
INSERT INTO products (name, price, description) VALUES ('Wireless Charging Pad', 29, 'Fast wireless charging pad for smartphones');
INSERT INTO products (name, price, description) VALUES ('Fitness Foam Roller', 29, 'High-density foam roller for muscle recovery');
INSERT INTO products (name, price, description) VALUES ('Yoga Mat', 39, 'Non-slip yoga mat for home workouts');
INSERT INTO products (name, price, description) VALUES ('Electric Scooter', 299, 'Foldable electric scooter for short commutes');
INSERT INTO products (name, price, description) VALUES ('LED Desk Lamp', 49, 'Adjustable LED desk lamp with USB charging port');
INSERT INTO products (name, price, description) VALUES ('Smart Home Security Camera', 129, 'Indoor smart home security camera with motion detection');
INSERT INTO products (name, price, description) VALUES ('Bluetooth Shower Speaker', 24, 'Waterproof Bluetooth speaker for shower use');
INSERT INTO products (name, price, description) VALUES ('Wireless Sport Earphones', 49, 'Sweatproof wireless earphones for sports');
INSERT INTO products (name, price, description) VALUES ('Robot Vacuum with Mop', 349, 'Robotic vacuum with mopping function');
INSERT INTO products (name, price, description) VALUES ('Wireless Charging Stand', 39, 'Charging stand for smartphones and smartwatches');
INSERT INTO products (name, price, description) VALUES ('Electric Bike', 799, 'Electric-assisted bicycle for urban commuting');
INSERT INTO products (name, price, description) VALUES ('Cordless Water Flosser', 59, 'Portable water flosser for oral hygiene');
INSERT INTO products (name, price, description) VALUES ('Smart Home Hub', 89, 'Central hub for controlling smart home devices');
INSERT INTO products (name, price, description) VALUES ('Fitness Tracker with GPS', 129, 'GPS-enabled fitness tracker for outdoor activities');
INSERT INTO products (name, price, description) VALUES ('Mini Projector', 179, 'Compact mini projector for presentations and movies');
INSERT INTO products (name, price, description) VALUES ('Portable Bluetooth Keyboard', 39, 'Foldable Bluetooth keyboard for smartphones and tablets');
INSERT INTO products (name, price, description) VALUES ('Portable Power Station', 299, 'High-capacity portable power station for camping');
INSERT INTO products (name, price, description) VALUES ('Bluetooth FM Transmitter', 19, 'Wireless FM transmitter for car audio');
INSERT INTO products (name, price, description) VALUES ('Wireless Charging Mouse Pad', 29, 'Mouse pad with integrated wireless charger');
INSERT INTO products (name, price, description) VALUES ('Stainless Steel Water Bottle', 19, 'Insulated stainless steel water bottle');
INSERT INTO products (name, price, description) VALUES ('Bluetooth Karaoke Microphone', 39, 'Wireless karaoke microphone with built-in speaker');
INSERT INTO products (name, price, description) VALUES ('Smart Ceiling Fan', 149, 'Wi-Fi-enabled ceiling fan with remote control');
INSERT INTO products (name, price, description) VALUES ('LED Strip Lights', 29, 'RGB LED strip lights with remote control');
INSERT INTO products (name, price, description) VALUES ('Portable Laptop Stand', 24, 'Adjustable laptop stand for better ergonomics');
INSERT INTO products (name, price, description) VALUES ('Handheld Milk Frother', 19, 'Battery-operated milk frother for coffee drinks');
INSERT INTO products (name, price, description) VALUES ('LED Bike Lights', 14, 'USB-rechargeable LED lights for bicycles');
INSERT INTO products (name, price, description) VALUES ('Smart Door Lock', 199, 'Keyless smart door lock with touchpad');
INSERT INTO products (name, price, description) VALUES ('Wireless Backup Camera', 49, 'Wireless rearview backup camera for vehicles');
INSERT INTO products (name, price, description) VALUES ('Fitness Resistance Bands', 29, 'Set of resistance bands for home workouts');
INSERT INTO products (name, price, description) VALUES ('Portable Clothes Steamer', 39, 'Travel-sized clothes steamer for wrinkle-free garments');
INSERT INTO products (name, price, description) VALUES ('Solar Power Bank', 49, 'Solar-powered portable power bank');
INSERT INTO products (name, price, description) VALUES ('Smart Water Leak Detector', 29, 'Wi-Fi-enabled water leak sensor for home safety');
INSERT INTO products (name, price, description) VALUES ('Cord Organizer', 14, 'Cable management organizer for desk or travel');
INSERT INTO products (name, price, description) VALUES ('Wireless Remote Control Outlet', 19, 'Remote-controlled electrical outlets for home automation');
INSERT INTO products (name, price, description) VALUES ('Smart Coffee Maker', 89, 'Wi-Fi-enabled coffee maker with app control');
INSERT INTO products (name, price, description) VALUES ('Portable Air Conditioner', 299, 'Mobile air conditioner for cooling small spaces');
INSERT INTO products (name, price, description) VALUES ('Smart Pet Feeder', 79, 'Automatic pet feeder with scheduling and portion control');
INSERT INTO products (name, price, description) VALUES ('Wireless Earbuds with Mic', 49, 'Wireless earbuds with built-in microphone');
INSERT INTO products (name, price, description) VALUES ('Fitness Tracker Watch', 69, 'Multi-function fitness watch with heart rate monitor');
INSERT INTO products (name, price, description) VALUES ('Mini Wi-Fi Camera', 39, 'Compact Wi-Fi camera for home monitoring');
INSERT INTO products (name, price, description) VALUES ('Gaming Keyboard', 69, 'Mechanical gaming keyboard with RGB lighting');
INSERT INTO products (name, price, description) VALUES ('Smart LED Bulb', 19, 'Wi-Fi-enabled LED bulb with voice control');
INSERT INTO products (name, price, description) VALUES ('Wireless Charging Car Mount', 39, 'Car mount with wireless charging for smartphones');
INSERT INTO products (name, price, description) VALUES ('Smart Light Switch', 29, 'Wi-Fi-enabled light switch for home automation');
INSERT INTO products (name, price, description) VALUES ('Electric Griddle', 49, 'Large electric griddle for cooking breakfast foods');
INSERT INTO products (name, price, description) VALUES ('Portable Bluetooth Speaker', 29, 'Compact and portable Bluetooth speaker');
INSERT INTO products (name, price, description) VALUES ('Smart Window Blinds', 99, 'Automated window blinds with remote control');
INSERT INTO products (name, price, description) VALUES ('Digital Meat Thermometer', 19, 'Instant-read digital meat thermometer');
INSERT INTO products (name, price, description) VALUES ('Smart Water Bottle', 29, 'Water bottle with hydration reminder and app integration');
INSERT INTO products (name, price, description) VALUES ('Mini Air Purifier', 49, 'Desktop air purifier for personal use');
INSERT INTO products (name, price, description) VALUES ('Gaming Headset Stand', 19, 'Headset stand with RGB lighting for gamers');
INSERT INTO products (name, price, description) VALUES ('Smart Desk Lamp', 39, 'Adjustable desk lamp with color temperature control');
INSERT INTO products (name, price, description) VALUES ('Wireless Charging Pad for Apple Watch', 29, 'Charging pad for wirelessly charging Apple Watch');
INSERT INTO products (name, price, description) VALUES ('Electric Pressure Cooker', 79, 'Multi-function electric pressure cooker');
INSERT INTO products (name, price, description) VALUES ('Smart Wi-Fi Plug', 19, 'Wi-Fi-enabled smart plug with energy monitoring');
INSERT INTO products (name, price, description) VALUES ('USB-C Hub', 29, 'Multi-port USB-C hub for laptops and devices');
INSERT INTO products (name, price, description) VALUES ('Wireless Touchpad Keyboard', 49, 'Keyboard with built-in touchpad for smart TVs');
INSERT INTO products (name, price, description) VALUES ('Robot Window Cleaner', 149, 'Automated window cleaning robot');
INSERT INTO products (name, price, description) VALUES ('Collapsible Silicone Food Storage Containers', 29, 'Set of space-saving food containers');
INSERT INTO products (name, price, description) VALUES ('Smart Garage Door Opener', 129, 'Wi-Fi-enabled garage door opener with remote control');
INSERT INTO products (name, price, description) VALUES ('LED Camping Lantern', 24, 'Portable LED lantern for camping and emergencies');
INSERT INTO products (name, price, description) VALUES ('Smart Baby Monitor', 99, 'Wi-Fi-enabled baby monitor with camera and app');
INSERT INTO products (name, price, description) VALUES ('Portable Espresso Maker', 49, 'Handheld espresso maker for coffee on the go');
INSERT INTO products (name, price, description) VALUES ('Gaming Controller Charging Station', 19, 'Charging dock for gaming controllers');
INSERT INTO products (name, price, description) VALUES ('Smart Plant Watering Kit', 39, 'Automated plant watering system with sensors');
INSERT INTO products (name, price, description) VALUES ('Mini Portable Fan', 14, 'USB-powered mini fan for personal cooling');
INSERT INTO products (name, price, description) VALUES ('Bluetooth Gamepad for Mobile Phones', 29, 'Wireless gamepad for mobile gaming');
INSERT INTO products (name, price, description) VALUES ('Automatic Soap Dispenser', 19, 'Touchless soap dispenser for improved hygiene');
INSERT INTO products (name, price, description) VALUES ('Smart Wi-Fi Router', 69, 'High-speed Wi-Fi router with parental controls');
INSERT INTO products (name, price, description) VALUES ('USB Desk Fan', 19, 'Quiet USB-powered fan for office use');
INSERT INTO products (name, price, description) VALUES ('Wireless Car Charger', 29, 'Qi wireless charger for car use');
INSERT INTO products (name, price, description) VALUES ('Smart Watering Timer', 29, 'Automated watering timer for garden irrigation');
INSERT INTO products (name, price, description) VALUES ('Folding Bluetooth Keyboard for Smartphones', 49, 'Compact folding keyboard for smartphones');
INSERT INTO products (name, price, description) VALUES ('Smart Wi-Fi Doorbell', 89, 'Video doorbell with motion detection and cloud storage');
INSERT INTO products (name, price, description) VALUES ('Fitness Balance Board', 39, 'Balance board for core and stability training');
INSERT INTO products (name, price, description) VALUES ('Mini Portable Projector Screen', 49, 'Collapsible projector screen for presentations');
INSERT INTO products (name, price, description) VALUES ('Car Phone Mount', 14, 'Universal phone mount for car dashboard');
INSERT INTO products (name, price, description) VALUES ('Smart Light Bulbs Starter Kit', 79, 'Set of smart light bulbs with hub');
INSERT INTO products (name, price, description) VALUES ('Wireless Backup External Hard Drive', 149, 'Portable external hard drive with automatic backup');
INSERT INTO products (name, price, description) VALUES ('Smart Wi-Fi Humidifier', 59, 'Wi-Fi-enabled humidifier with adjustable mist levels');
INSERT INTO products (name, price, description) VALUES ('Portable UV Sanitizer', 24, 'UV sanitizer for disinfecting small items');
INSERT INTO products (name, price, description) VALUES ('Smart Window Curtains', 99, 'Automated window curtains with remote control');
INSERT INTO products (name, price, description) VALUES ('Portable Laptop Desk', 29, 'Foldable laptop desk for comfortable computing');
INSERT INTO products (name, price, description) VALUES ('Electric Bug Zapper', 39, 'Indoor and outdoor bug zapper with UV light');
INSERT INTO products (name, price, description) VALUES ('Smart RGB Light Strip', 29, 'Wi-Fi-enabled RGB light strip with music sync');
INSERT INTO products (name, price, description) VALUES ('Smart Wi-Fi Thermostat', 129, 'Programmable thermostat with app control');
INSERT INTO products (name, price, description) VALUES ('Wireless Gaming Controller', 49, 'Bluetooth gaming controller for consoles and PC');
INSERT INTO products (name, price, description) VALUES ('Smart Water Leak Sensor', 19, 'Wireless water leak detector for home protection');
INSERT INTO products (name, price, description) VALUES ('Portable Bluetooth Keyboard for Tablets', 39, 'Slim and portable keyboard for tablets');
INSERT INTO products (name, price, description) VALUES ('Wireless Touchpad Mouse', 29, 'Multi-touch wireless mouse for laptops');
INSERT INTO products (name, price, description) VALUES ('Mini HD Action Camera', 79, 'Compact action camera for recording adventures');
INSERT INTO products (name, price, description) VALUES ('Smart Wi-Fi Socket', 24, 'Wi-Fi-enabled smart socket with energy monitoring');
INSERT INTO products (name, price, description) VALUES ('Portable Neck Fan', 19, 'Hands-free neck fan for outdoor activities');
INSERT INTO products (name, price, description) VALUES ('Smart Home Weather Station', 69, 'Wireless weather station with indoor and outdoor sensors');
INSERT INTO products (name, price, description) VALUES ('Cordless Electric Kettle', 39, 'Rapid-boil cordless kettle for hot beverages');
INSERT INTO products (name, price, description) VALUES ('Smart Plant Monitor', 29, 'Sensor-based plant monitor with app notifications');
INSERT INTO products (name, price, description) VALUES ('Fitness Exercise Ball', 19, 'Anti-burst exercise ball for workouts');
INSERT INTO products (name, price, description) VALUES ('Portable Wireless Mouse', 24, 'Compact wireless mouse for travel');
INSERT INTO products (name, price, description) VALUES ('Smart Wi-Fi Light Switch', 29, 'Wi-Fi-enabled light switch with voice control');
INSERT INTO products (name, price, description) VALUES ('USB-Powered Desk Heater', 29, 'Mini desktop heater for personal warmth');
INSERT INTO products (name, price, description) VALUES ('Smart Wi-Fi Security Camera', 49, 'Indoor and outdoor security camera with cloud storage');
INSERT INTO products (name, price, description) VALUES ('Yoga Blocks', 19, 'Set of yoga blocks for support and stability');
INSERT INTO products (name, price, description) VALUES ('Wireless Bluetooth Ear Muffs', 39, 'Bluetooth ear muffs with built-in speakers');
INSERT INTO products (name, price, description) VALUES ('Smart Home Door Sensor', 19, 'Wireless door sensor for home security');
INSERT INTO products (name, price, description) VALUES ('Bluetooth Beanie', 24, 'Knit beanie with built-in wireless headphones');
INSERT INTO products (name, price, description) VALUES ('Portable Air Compressor', 59, 'Compact air compressor for inflating tires and sports equipment');
INSERT INTO products (name, price, description) VALUES ('Smart Drawer Organizer', 39, 'Electronic drawer organizer with app control');
INSERT INTO products (name, price, description) VALUES ('LED Bike Helmet', 49, 'Bicycle helmet with integrated LED lights');
INSERT INTO products (name, price, description) VALUES ('Smart Wi-Fi Water Pitcher', 29, 'Wi-Fi-enabled water pitcher with filter status tracking');
INSERT INTO products (name, price, description) VALUES ('Wireless Bluetooth Car Adapter', 19, 'Bluetooth adapter for car audio systems');
INSERT INTO products (name, price, description) VALUES ('Smart Air Purifier', 129, 'Wi-Fi-enabled air purifier with air quality monitoring');
INSERT INTO products (name, price, description) VALUES ('Travel Neck Pillow', 19, 'Memory foam neck pillow for travel comfort');
INSERT INTO products (name, price, description) VALUES ('Smart Pet Tracker', 49, 'GPS pet tracker with activity monitoring');
INSERT INTO products (name, price, description) VALUES ('Gaming Mouse Pad', 14, 'Large mouse pad optimized for gaming');
INSERT INTO products (name, price, description) VALUES ('Smart Wi-Fi Power Strip', 39, 'Wi-Fi-enabled power strip with individual outlets control');
INSERT INTO products (name, price, description) VALUES ('Mini Bluetooth Printer', 79, 'Portable Bluetooth printer for mobile printing');
INSERT INTO products (name, price, description) VALUES ('Wireless Charging Desk Organizer', 49, 'Desktop organizer with integrated wireless charger');
INSERT INTO products (name, price, description) VALUES ('Smart Watering Can', 29, 'Automatic watering can with precise pouring');
INSERT INTO products (name, price, description) VALUES ('Bluetooth Remote Shutter', 14, 'Remote shutter for smartphone photography');
INSERT INTO products (name, price, description) VALUES ('Smart Wi-Fi Air Fryer', 99, 'Wi-Fi-enabled air fryer with recipe app');
INSERT INTO products (name, price, description) VALUES ('Portable Handheld Fan', 19, 'Mini handheld fan with adjustable speed');
INSERT INTO products (name, price, description) VALUES ('Smart Voice Translator', 69, 'Language translator with voice recognition');
INSERT INTO products (name, price, description) VALUES ('Wireless Bluetooth FM Radio', 29, 'Bluetooth FM radio with SD card support');
INSERT INTO products (name, price, description) VALUES ('Smart Doorbell Camera', 89, 'Video doorbell with motion detection and two-way audio');
INSERT INTO products (name, price, description) VALUES ('Portable LED Work Light', 24, 'Rechargeable LED work light for projects');
INSERT INTO products (name, price, description) VALUES ('Smart Pet Water Fountain', 49, 'Wi-Fi-enabled water fountain for pets');
INSERT INTO products (name, price, description) VALUES ('Cordless Handheld Fan', 14, 'Handheld fan with USB rechargeability');
INSERT INTO products (name, price, description) VALUES ('LED Desk Clock', 29, 'Desk clock with adjustable LED display');
INSERT INTO products (name, price, description) VALUES ('Smart Wi-Fi Vacuum Sealer', 79, 'Vacuum sealer with app control for food preservation');
INSERT INTO products (name, price, description) VALUES ('Portable Folding Camping Table', 39, 'Compact folding table for outdoor use');
INSERT INTO products (name, price, description) VALUES ('Smart Night Light', 19, 'Motion-activated night light with color changing');
INSERT INTO products (name, price, description) VALUES ('Mini Wireless Keyboard with Touchpad', 29, 'Compact wireless keyboard with touchpad');
INSERT INTO products (name, price, description) VALUES ('Smart Plant Pot', 39, 'Self-watering plant pot with app monitoring');
